export const venueMap: Record<string, string> = {
  // ── Premier League ──────────────────────────────────────────
  'Arsenal FC': 'Emirates Stadium',
  'Aston Villa FC': 'Villa Park',
  'Bournemouth AFC': 'Vitality Stadium',
  'Brentford FC': 'Gtech Community Stadium',
  'Brighton & Hove Albion FC': 'Amex Stadium',
  'Chelsea FC': 'Stamford Bridge',
  'Crystal Palace FC': 'Selhurst Park',
  'Everton FC': 'Goodison Park',
  'Fulham FC': 'Craven Cottage',
  'Ipswich Town FC': 'Portman Road',
  'Leicester City FC': 'King Power Stadium',
  'Liverpool FC': 'Anfield',
  'Manchester City FC': 'Etihad Stadium',
  'Manchester United FC': 'Old Trafford',
  'Newcastle United FC': "St. James' Park",
  'Nottingham Forest FC': 'City Ground',
  'Southampton FC': "St. Mary's Stadium",
  'Tottenham Hotspur FC': 'Tottenham Hotspur Stadium',
  'West Ham United FC': 'London Stadium',
  'Wolverhampton Wanderers FC': 'Molineux Stadium',
  'Leeds United FC': 'Elland Road',
  'West Bromwich Albion FC': 'The Hawthorns',
  'Sheffield United FC': 'Bramall Lane',

  // ── La Liga ─────────────────────────────────────────────────
  'Athletic Club': 'Estadio de San Mamés',
  'Atlético de Madrid': 'Cívitas Metropolitano',
  'CA Osasuna': 'Estadio El Sadar',
  'Deportivo Alavés': 'Estadio de Mendizorroza',
  'FC Barcelona': 'Estadi Olímpic Lluís Companys',
  'Getafe CF': 'Coliseum Alfonso Pérez',
  'Girona FC': 'Estadio Municipal de Montilivi',
  'UD Las Palmas': 'Estadio Gran Canaria',
  'CD Leganés': 'Estadio Municipal de Butarque',
  'RCD Mallorca': 'Estadio de Son Moix',
  'Real Betis Balompié': 'Estadio Benito Villamarín',
  'Real Madrid CF': 'Estadio Santiago Bernabéu',
  'Real Sociedad de Fútbol': 'Reale Arena',
  'Real Valladolid CF': 'Estadio José Zorrilla',
  'Rayo Vallecano de Madrid': 'Estadio de Vallecas',
  'Sevilla FC': 'Estadio Ramón Sánchez-Pizjuán',
  'UD Espanyol de Barcelona': 'Stage Front Stadium',
  'Valencia CF': 'Estadio Mestalla',
  'Villarreal CF': 'Estadio de la Cerámica',
  'Club Atlético de Madrid': 'Cívitas Metropolitano',
  'RC Celta de Vigo': 'Abanca-Balaídos',

  // ── Bundesliga ───────────────────────────────────────────────
  'FC Augsburg': 'WWK Arena',
  'Bayer 04 Leverkusen': 'BayArena',
  'Bayern München': 'Allianz Arena',
  'VfL Bochum 1848': 'Vonovia Ruhrstadion',
  'Borussia Dortmund': 'Signal Iduna Park',
  'Borussia Mönchengladbach': 'Borussia-Park',
  'Eintracht Frankfurt': 'Deutsche Bank Park',
  'SC Freiburg': 'Europa-Park Stadion',
  'TSG 1899 Hoffenheim': 'PreZero Arena',
  'Holstein Kiel': 'Holstein-Stadion',
  'RB Leipzig': 'Red Bull Arena',
  '1. FSV Mainz 05': 'MEWA Arena',
  'SC Paderborn 07': 'Benteler-Arena',
  'FC St. Pauli 1910': 'Millerntor-Stadion',
  'VfB Stuttgart': 'MHPArena',
  '1. FC Union Berlin': 'Stadion An der Alten Försterei',
  'Werder Bremen': 'wohninvest Weserstadion',
  'VfL Wolfsburg': 'Volkswagen Arena',
  'Hamburger SV': 'Volksparkstadion',
  'Fortuna Düsseldorf': 'Merkur Spiel-Arena',
  'Karlsruher SC': 'Wildparkstadion',

  // ── Serie A ──────────────────────────────────────────────────
  'Atalanta BC': 'Gewiss Stadium',
  'Bologna FC 1909': 'Stadio Renato Dall\'Ara',
  'Cagliari Calcio': 'Unipol Domus',
  'Como 1907': 'Stadio Giuseppe Sinigaglia',
  'ACF Fiorentina': 'Stadio Artemio Franchi',
  'Genoa CFC': 'Stadio Luigi Ferraris',
  'FC Internazionale Milano': 'San Siro',
  'Juventus FC': 'Allianz Stadium',
  'SS Lazio': 'Stadio Olimpico',
  'AC Milan': 'San Siro',
  'AC Monza': 'Stadio Brianteo',
  'SSC Napoli': 'Stadio Diego Armando Maradona',
  'Parma Calcio 1913': 'Stadio Ennio Tardini',
  'AS Roma': 'Stadio Olimpico',
  'US Lecce': 'Stadio Via del Mare',
  'UC Sampdoria': 'Stadio Luigi Ferraris',
  'US Salernitana 1919': 'Stadio Arechi',
  'Torino FC': 'Stadio Olimpico Grande Torino',
  'Udinese Calcio': 'Bluenergy Stadium',
  'Venezia FC': 'Stadio Pier Luigi Penzo',
  'Hellas Verona FC': 'Stadio Marcantonio Bentegodi',
  'Empoli FC': 'Stadio Carlo Castellani',
  'Spezia Calcio': 'Stadio Alberto Picco',

  // ── Ligue 1 ──────────────────────────────────────────────────
  'Angers SCO': 'Stade Raymond-Kopa',
  'AJ Auxerre': 'Stade de l\'Abbé-Deschamps',
  'Stade Brestois 29': 'Stade Francis-Le Blé',
  'RC Lens': 'Stade Bollaert-Delelis',
  'LOSC Lille': 'Stade Pierre-Mauroy',
  'Olympique Lyonnais': 'Groupama Stadium',
  'Olympique de Marseille': 'Stade Vélodrome',
  'AS Monaco FC': 'Stade Louis II',
  'Montpellier HSC': 'Stade de la Mosson',
  'FC Nantes': 'Stade de la Beaujoire',
  'OGC Nice': 'Allianz Riviera',
  'Paris Saint-Germain FC': 'Parc des Princes',
  'Stade de Reims': 'Stade Auguste-Delaune',
  'Stade Rennais FC 1901': 'Roazhon Park',
  'RC Strasbourg Alsace': 'Stade de la Meinau',
  'Toulouse FC': 'Stadium de Toulouse',
  'Le Havre AC': 'Stade Océane',
  'Saint-Étienne': 'Stade Geoffroy-Guichard',
  'Girondins de Bordeaux': 'Matmut Atlantique',
  'Sporting Club de Bastia': 'Stade Armand-Cesari',
  'Clermont Foot 63': 'Stade Gabriel-Montpied',
};